package com.itantra.translate

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Diffs the Kotlin port of IndicTrans2's text processing against AI4Bharat's reference.
 *
 * `mt-golden.tsv` is generated by `model-export/make_mt_golden.py`, which runs the
 * reference IndicProcessor and the real int8 models over an English corpus and over the
 * model's own translations of it into all nine Indic languages. A drifted port does not
 * fail loudly on a phone — it feeds the model text it was not trained on and gets back a
 * fluent, wrong sentence — so every case must match exactly.
 */
class IndicTransTextTest {

    private data class Case(
        val kind: String, val src: String, val tgt: String,
        val input: String, val decoded: String, val expected: String
    )

    private val cases: List<Case> by lazy {
        val stream = javaClass.classLoader!!.getResourceAsStream("mt-golden.tsv")
            ?: error("mt-golden.tsv missing from test resources")
        stream.bufferedReader(Charsets.UTF_8).readLines()
            .filter { it.isNotBlank() && !it.startsWith("#") }
            .map { line ->
                val f = line.split('\t')
                Case(f[0], f[1], f[2], f[3], f[4], f[5])
            }
    }

    @Test
    fun `preprocessing matches the reference`() {
        val rows = cases.filter { it.kind == "pre" }
        assertTrue("expected golden rows", rows.size > 200)
        val failures = rows.mapNotNull { c ->
            val got = IndicTransText.preprocess(c.input, c.src).text
            if (got == c.expected) null else "[${c.src}] ${c.input}\n   want: ${c.expected}\n   got : $got"
        }
        assertEquals(
            "${failures.size}/${rows.size} preprocessing mismatches:\n" + failures.take(15).joinToString("\n"),
            0, failures.size
        )
    }

    @Test
    fun `postprocessing matches the reference`() {
        val rows = cases.filter { it.kind == "post" }
        assertTrue("expected golden rows", rows.size > 200)
        val failures = rows.mapNotNull { c ->
            val placeholders = IndicTransText.preprocess(c.input, c.src).placeholders
            val got = IndicTransText.postprocess(c.decoded, c.tgt, placeholders)
            if (got == c.expected) null else "[${c.src}->${c.tgt}] ${c.decoded}\n   want: ${c.expected}\n   got : $got"
        }
        assertEquals(
            "${failures.size}/${rows.size} postprocessing mismatches:\n" + failures.take(15).joinToString("\n"),
            0, failures.size
        )
    }

    @Test
    fun `phone numbers survive as placeholders`() {
        val p = IndicTransText.preprocess("Call 98765-43210 now", "en")
        assertEquals("Call < ID1 > now", p.text)
        assertEquals("98765-43210", p.placeholders["<ID1>"])
        assertEquals(
            "உடனே 98765-43210 அழைக்கவும்",
            IndicTransText.postprocess("उडऩे < ID1 > अऴैक्कवुम्", "ta", p.placeholders)
        )
    }

    @Test
    fun `indic scripts round trip through devanagari`() {
        for ((lang, text) in listOf("ta" to "தண்ணீர்", "bn" to "জল", "te" to "నీళ్ళు", "ml" to "വെള്ളം", "gu" to "પાણી")) {
            val deva = IndicTransText.transliterate(text, lang, "hi")
            assertTrue("$lang should map into Devanagari: $deva", deva.all { it.code in 0x0900..0x097F })
            assertEquals(text, IndicTransText.transliterate(deva, "hi", lang))
        }
    }

    @Test
    fun `a colon after a number is left alone`() {
        // The reference's double-escaped visarga rule turns "5:" into the literal "\1ः".
        assertEquals("५:३० बजे", IndicTransText.IndicNormalizer.normalize("५:३० बजे", "hi"))
    }
}
